### ISSUE TITLE
A license is required to restore order to verse

### ISSUE THREAD

**Issue by gl-yziquel** [gregr/experiments#1]
Hi.

I cloned your repo and attempted to restore order to the universe, as per your README.

https://github.com/gl-yziquel/gregr-verse

Your code seems to be the only implementation of the verse calculus that I know to be publicly available on the net.

A license would be most welcomed.

**Comment by gregr** [comment]
Sure, would the MIT license work for you?

**Comment by gregr** [comment]
Added LICENSE in: a7c8cf1430b1ec38b4adc9f1fb9cc3409dc0a34b

**Comment by gl-yziquel** [comment]
I'm personally of the GPLv4 or v5 religion, but I will tolerate a mild amount of heresy. MIT is fine.

Thank you so much.
